Sys.setenv(OPENGWAS_JWT = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImFwaS1qd3QiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhcGkub3Blbmd3YXMuaW8iLCJhdWQiOiJhcGkub3Blbmd3YXMuaW8iLCJzdWIiOiIyMTE5ODk2NTg5QHFxLmNvbSIsImlhdCI6MTcxNzIzMDgxMywiZXhwIjoxNzE4NDQwNDEzfQ.L1oBlSD9-kehous9V-oHqJGCxPubkVynT1MCb1QYjKFB9r87z7QarvswxtJgDEeBMJm01VgzdHZq6PI2cOyFfratZVLBlRpbor_VewKHyFR5-dw3Ge4gq2reUb4UETLodM7DD91Pnhfb4ltcvqTIrFW-HnBynjfc28pb2XdXgdwCnSixsOIlNa6jgYXL1OvqvJGJYbwutyxO0y4Qx7X-85goHXB6AXgkiGzBvt-WDq1NBzRG0ihqOqivcxoYkynvw4KJGBFPIWZe5HcCtMbon_LCVl0vGvdHPB6KQ_OVh7400gkL5yRkrhP19JuQbb43yhwm0vGYKOSDkOtjUmKZlQ")
ieugwasr::get_opengwas_jwt()
remotes::install_github("MRCIEU/TwoSampleMR")
remotes::install_github("mrcieu/ieugwasr")
